### ISSUE TITLE
createLiveFaceDetector returns null and controller.isFacialAllowed returns false

### ISSUE THREAD

**Issue by rramprasad** [Acuant/AcuantAndroidMobileSDKV10#2]
I have tried to start Face detection in my fragment, but always createLiveFaceDetector returns null, so camera preview not displayed.

`controller.createLiveFaceDetector(activity, this@FaceDetectionFragment)`

I already added following meta data in AndroidManifest.xml
```
<meta-data
            android:name="com.google.android.gms.vision.DEPENDENCIES"
            android:value="face" />
```

When try to log, `controller.isFacialAllowed -> false`

Is it any other configurations I need to add to use FaceDetection?

**Comment by tbehera** [comment]
@rramprasad Please create a support ticket at https://support.acuant.com so that we can retrieve your credentials to reproduce the issue.

**Comment by rramprasad** [comment]
This issue has been fixed after adding **healthInsuranceEndpoint** and **idEndpoint** on credential endpoints while initialize AcuantSDK.

**Comment by Kaviyarasan-M** [comment]
Thank you, now its working fine

*Kaviyarasan M*
Android & Mean Stack Developer
m: +91 8012209155
e: kavihari13@gmail.com


.
<https://www.facebook.com/kaviyarasan1995?lst=100005033974209%3A100005033974209%3A1499338285>
. <https://twitter.com/kavihari13>.
<https://www.linkedin.com/in/kaviyarasan-m/>.
